title: Jedrick Regala Zablan
logo: /assets/headshot.jpg
description: I am a UC Berkeley MSSE graduate actively seeking to leverage my skills in software development, machine learning and data analysis.
#show_download true 
theme: jekyll-theme-minimal
minima:
  social_links:
    github: https://github.com/JedrickZablan
    linkedin: https://www.linkedin.com/in/jedrick-zablan-1967041a5/
author:
  email: jedrickzablan@berkeley.edu
  phone: 619-870-7177

