title: Jedrick Regala Zablan
logo: /assets/headshot.jpg
description: I am a current Molecular Sciences and Software Engineering Master's student at UC Berkeley, actively seeking internship opportunities to leverage my skills in data analysis, machine learning, and software development.
#show_download true 
theme: jekyll-theme-minimal
minima:
  social_links:
    github: https://github.com/JedrickZablan
    linkedin: https://www.linkedin.com/in/jedrick-zablan-1967041a5/
author:
  email: jedrickzablan@berkeley.edu
  phone: 619-870-7177

