title: Jedrick Regala Zablan
logo: /assets/headshot.jpg
description: I’m a UC Berkeley MSSE graduate driven to apply my experience in software engineering, machine learning, and data analysis to solve meaningful problems in tech and science.
#show_download true 
theme: jekyll-theme-minimal
minima:
  social_links:
    github: https://github.com/JedrickZablan
    linkedin: https://www.linkedin.com/in/jedrick-zablan-1967041a5/
author:
  email: jedrickzablan@berkeley.edu
  phone: 619-870-7177

